/**
 * Author:  jlopes
 * Created: 28 de mai. de 2024
 */

INSERT INTO USUARIO(LOGIN_USUARIO, SENHA, NOME_USUARIO) VALUES('LOPES', '$2a$12$BtgrXoA0JPq6t9SNdJBMnOMXxneseEvb4iLyaZxjUVt3xG6dHBCdS', 'JAMMERSON LOPES');
INSERT INTO USUARIO(LOGIN_USUARIO, SENHA, NOME_USUARIO) VALUES('NEIDE', '$2a$12$BtgrXoA0JPq6t9SNdJBMnOMXxneseEvb4iLyaZxjUVt3xG6dHBCdS', 'EDINEIDE MARIA GOMES');
