/**
 * Author:  jlopes
 * Created: 28 de mai. de 2024
 */

INSERT INTO USUARIO(LOGIN_USUARIO, SENHA, NOME_USUARIO) VALUES('APOIO', '$2y$10$gOqrPUaKHyKhlUsF8tli1.F3iaVY8IJo1thjJBNfTuDVJEego5Ume', 'APOIO ADMINISTRADOR');
INSERT INTO USUARIO(LOGIN_USUARIO, SENHA, NOME_USUARIO) VALUES('DELTA', '$2y$10$Hc6.WaqcttWYZK1A4yPQQOxnjouFpopOSmLQ8qaHbbDkrqY9DbxxO', 'DELTA USUARIO');

/*
APOIO -> apoio2024
DELTA -> delta2024
*/
